// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhky4eaIOXOdXO9hXct7JOGMS71kkNrcw',
    appId: '1:953178718235:android:2d1ee9cb72dd9ec6a3f8be',
    messagingSenderId: '953178718235',
    projectId: 'flutter-login-307ae',
    storageBucket: 'flutter-login-307ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi8tKJGR4w2plhm0XZMJ1KYDxSPigy_1A',
    appId: '1:953178718235:ios:c2da80d3a75eac93a3f8be',
    messagingSenderId: '953178718235',
    projectId: 'flutter-login-307ae',
    storageBucket: 'flutter-login-307ae.firebasestorage.app',
    androidClientId: '953178718235-rdf6eg3po3g6t4ljajmcpnc416dndhbn.apps.googleusercontent.com',
    iosClientId: '953178718235-1ejcuscvmqtumm4ii6ohghvjg1uqrptb.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq8srtFffsPiZ2UXnyDJNBftqQd_cHPtI',
    appId: '1:953178718235:web:b8d90a5a090a99baa3f8be',
    messagingSenderId: '953178718235',
    projectId: 'flutter-login-307ae',
    authDomain: 'flutter-login-307ae.firebaseapp.com',
    storageBucket: 'flutter-login-307ae.firebasestorage.app',
    measurementId: 'G-7GSQL8DN9V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi8tKJGR4w2plhm0XZMJ1KYDxSPigy_1A',
    appId: '1:953178718235:ios:c2da80d3a75eac93a3f8be',
    messagingSenderId: '953178718235',
    projectId: 'flutter-login-307ae',
    storageBucket: 'flutter-login-307ae.firebasestorage.app',
    androidClientId: '953178718235-rdf6eg3po3g6t4ljajmcpnc416dndhbn.apps.googleusercontent.com',
    iosClientId: '953178718235-1ejcuscvmqtumm4ii6ohghvjg1uqrptb.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq8srtFffsPiZ2UXnyDJNBftqQd_cHPtI',
    appId: '1:953178718235:web:c2e014987a341806a3f8be',
    messagingSenderId: '953178718235',
    projectId: 'flutter-login-307ae',
    authDomain: 'flutter-login-307ae.firebaseapp.com',
    storageBucket: 'flutter-login-307ae.firebasestorage.app',
    measurementId: 'G-ZYYN2JS1NL',
  );

}